# 누락 상권 조사 (유동인구, 추정매출)

In [1]:
# 필요한 라이브러리 불러오기

import pandas as pd

## 1. 데이터 불러오기

In [2]:
# 데이터 경로 설정
data_path = 'data/'

# 데이터 불러오기
# 상권정보 데이터
df0 = pd.read_csv(data_path + '서울시 우리마을가게 상권분석서비스(상권영역).csv', encoding = 'cp949')

# 유동인구 데이터
df1 = pd.read_csv(data_path + '서울시 우리마을가게 상권분석서비스(상권-추정유동인구)_new.csv', encoding = 'cp949')

# 추정매출 데이터
df2_2020 = pd.read_csv(data_path + '서울시 우리마을가게 상권분석서비스(상권-추정매출)_2020.csv', encoding = 'cp949')
df2_2019 = pd.read_csv(data_path + '서울시 우리마을가게 상권분석서비스(상권-추정매출)_2019.csv', encoding = 'cp949')
df2_2018 = pd.read_csv(data_path + '서울시 우리마을가게 상권분석서비스(상권-추정매출)_2018.csv', encoding = 'cp949')
df2_2017 = pd.read_csv(data_path + '서울시 우리마을가게 상권분석서비스(상권-추정매출)_2017.csv', encoding = 'cp949')
df2_2016 = pd.read_csv(data_path + '서울시 우리마을가게 상권분석서비스(상권-추정매출)_2016.csv', encoding = 'cp949')
df2_2015 = pd.read_csv(data_path + '서울시 우리마을가게 상권분석서비스(상권-추정매출)_2015.csv', encoding = 'cp949')

In [3]:
# 기준이 되는 상권정보

df0.head()

,기준_년월_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,상권_코드_명,엑스좌표_값,와이좌표_값,시군구_코드,행정동_코드,형태정보
0,201810,R,전통시장,1001453,낙성대시장,196121,442084,11620,11620585,NaN
1,201810,R,전통시장,1001454,봉천제일종합시장,195147,442413,11620,11620595,NaN
2,201810,R,전통시장,1001474,도곡시장,204551,444227,11680,11680650,NaN
3,201810,R,전통시장,1001475,강남개포시장,206065,443310,11680,11680670,NaN
4,201810,R,전통시장,1001412,화곡본동시장,186203,449328,11500,11500590,NaN

In [4]:
# 기준 상권코드를 추출
sts = set(df0['상권_코드'])
len(sts)

## 2. 누락 상권 조사
### (1) 유동인구

In [6]:
# 데이터셋 연도별, 분기별 분할
start_year = 2015 # 시작 연도
end_year = 2020 # 끝 연도
start_quarter = 1 # 시작 분기
end_quarter = 4 # 끝 분기

for i in range(start_year, end_year + 1):
    df = df1[df1['기준_년_코드'] == i]
    for j in range(start_quarter, end_quarter + 1):
        globals()['df1_{}_{}'.format(i, j)] = df[df['기준_분기_코드'] == j]
        if i == start_year and j == end_quarter - 2: # 2020년은 2분기까지 밖에 없으므로 조기 종료
            break

In [8]:
# 연도, 분기별 상권 개수 출력

for i in range(start_year, end_year + 1):
    for j in range(start_quarter, end_quarter + 1):
        print(len(globals()['df1_{}_{}'.format(i, j)]))
        if i == start_year and j == end_quarter - 2: # 2020년은 2분기까지 밖에 없으므로 조기 종료
            break

1495
1495
1495
1495
1495
1495
1495
1495
1495
1495
1495
1495
1495
1495
1486
1495
1495
1495
1486
1485
1486
1486

In [ ]:
# 어떤 상권이 빠졌는지 조사

for i in range(start_year, end_year + 1):
    for j in range(start_quarter, end_quarter + 1):
        globals()['s1_{}_{}'.format(i, j)] = set(globals()['df1_{}_{}'.format(i, j)]['상권_코드'])
        if i == start_year and j == end_quarter - 2: # 2020년은 2분기까지 밖에 없으므로 조기 종료
            break
            
for i in range(start_year, end_year + 1):
    for j in range(start_quarter, end_quarter + 1):
        globals()['d1_{}_{}'.format(i, j)] = globals()['s1_{}_{}'.format(i, j)]
        if i == start_year and j == end_quarter - 2: # 2020년은 2분기까지 밖에 없으므로 조기 종료
            break

In [12]:
# 연도별, 분기별 빠진 상권의 상권 코드 출력

for i in range(start_year, end_year + 1):
    for j in range(start_quarter, end_quarter + 1):
        print("{}_{} : {}".format(i, j, globals()['d1_{}_{}'.format(i, j)]))
        if i == start_year and j == end_quarter - 2: # 2020년은 2분기까지 밖에 없으므로 조기 종료
            break

2020_1 : {1001278}
2020_2 : {1001278}
2019_1 : {1001278}
2019_2 : {1001278}
2019_3 : {1001278}
2019_4 : {1001278}
2018_1 : {1001278}
2018_2 : {1001278}
2018_3 : {1001278}
2018_4 : {1001278}
2017_1 : {1001278}
2017_2 : {1001278}
2017_3 : {1001278}
2017_4 : {1001278}
2016_1 : {1001250, 1001383, 1001258, 1001278, 1001328, 1001393, 1001269, 1001371, 1001020, 1001086}
2016_2 : {1001278}
2016_3 : {1001278}
2016_4 : {1001278}
2015_1 : {1001250, 1001383, 1001258, 1001278, 1001328, 1001393, 1001269, 1001371, 1001020, 1001086}
2015_2 : {1001250, 1001383, 1001258, 1001086, 1001278, 1001328, 1001393, 1001269, 1001371, 1001020, 1001118}
2015_3 : {1001250, 1001383, 1001258, 1001278, 1001328, 1001393, 1001269, 1001371, 1001020, 1001086}
2015_4 : {1001250, 1001383, 1001258, 1001278, 1001328, 1001393, 1001269, 1001371, 1001020, 1001086}

In [17]:
# 누락된 상권의 상권명 출력

market_code_list = list(df['상권_코드'].unique())
market_name_list = list(df['상권_코드_명'].unique())

# 누락된 상권 코드 저장
total_code_list = [] 
for i in range(start_year, end_year + 1):
    for j in range(start_quarter, end_quarter + 1):
        total_code_list.append(list(globals()['d1_{}_{}'.format(i, j)]))
        if i == start_year and j == end_quarter - 2: # 2020년은 2분기까지 밖에 없으므로 조기 종료
            break
            
# 상권 코드에 대응하는 상권명 저장
total_code_list = []
for code_list in total_code_list:
    for code in code_list:
        name_list = []
        ind = marekt_code_list.index(code)
        name = market_name_list[ind]
        name_list.append(name)
    total_code_list.append(name_list)
    

# 결과 출력
n = 0
for i in range(start_year, end_year + 1):
    for j in range(start_quarter, end_quarter + 1):
        print("{}_{} : {}".format(i, j, total_code_list[n]))
        if i == start_year and j == end_quarter - 2: # 2020년은 2분기까지 밖에 없으므로 조기 종료
            break

2020_1 : ['남평화시장']

2020_2 : ['남평화시장']

2019_1 : ['남평화시장']

2019_2 : ['남평화시장']

2019_3 : ['남평화시장']

2019_4 : ['남평화시장']

2018_1 : ['남평화시장']

2018_2 : ['남평화시장']

2018_3 : ['남평화시장']

2018_4 : ['남평화시장']

2017_1 : ['남평화시장']

2017_2 : ['남평화시장']

2017_3 : ['남평화시장']

2017_4 : ['남평화시장']

2016_1 : ['서울 은평구 불광역_3', '공덕시장', '등나무근린공원 주변', '남평화시장', '이문제일시장', '마포농수산물시장', '동문시장', '대조시장', '장지역', '고속터미널역']

2016_2 : ['남평화시장']

2016_3 : ['남평화시장']

2016_4 : ['남평화시장']

2015_1 : ['서울 은평구 불광역_3', '공덕시장', '등나무근린공원 주변', '남평화시장', '이문제일시장', '마포농수산물시장', '동문시장', '대조시장', '장지역', '고속터미널역']

2015_2 : ['서울 은평구 불광역_3', '공덕시장', '등나무근린공원 주변', '고속터미널역', '남평화시장', '이문제일시장', '마포농수산물시장', '동문시장', '대조시장', '장지역', '문래동 주민센터']

2015_3 : ['서울 은평구 불광역_3', '공덕시장', '등나무근린공원 주변', '남평화시장', '이문제일시장', '마포농수산물시장', '동문시장', '대조시장', '장지역', '고속터미널역']

2015_4 : ['서울 은평구 불광역_3', '공덕시장', '등나무근린공원 주변', '남평화시장', '이문제일시장', '마포농수산물시장', '동문시장', '대조시장', '장지역', '고속터미널역']

- 유동인구는 KT LTE 시그널 데이터를 이용하여 기지국 당 특정 시점의 생활인구를 구하고 이를 전체 인구 기준으로 변환하여 기지국 범위 내의 구역에 배분하는 방식  
- 해당 상권에 해당하는 기지국을 찾고 직접 값을 구하는 방식은 매우 복잡해 보이고, KT에서도 기지국에 기록된 생활인구를 어떻게 각 지역에 배분하는지는 공개하지 않음  
- 누락된 상권과 인접한 상권의 유동인구로 대체하는 방식이 더 좋아 보임  
- 하지만 서울 우리마을가게 상권 분석 서비스에서는 누락 상권의 유동인구를 0으로 취급함

### (2) 추정 매출 빠진 상권 조사

In [18]:
# 데이터셋 연도별, 분기별 분할
start_year = 2015 # 시작 연도
end_year = 2020 # 끝 연도
start_quarter = 1 # 시작 분기
end_quarter = 4 # 끝 분기

for i in range(start_year, end_year + 1):
    for j in range(start_quarter, end_quarter + 1):
        globals()['df2_{}_{}'.format(i, j)] = df[df['기준_분기_코드'] == j]
        if i == start_year and j == end_quarter - 2: # 2020년은 2분기까지 밖에 없으므로 조기 종료
            break

In [19]:
# 연도, 분기별 상권 개수 출력

for i in range(start_year, end_year + 1):
    for j in range(start_quarter, end_quarter + 1):
        print(len(globals()['df2_{}_{}'.format(i, j)]))
        if i == start_year and j == end_quarter - 2: # 2020년은 2분기까지 밖에 없으므로 조기 종료
            break

In [21]:
# 어떤 상권이 빠졌는지 조사

for i in range(start_year, end_year + 1):
    for j in range(start_quarter, end_quarter + 1):
        globals()['s2_{}_{}'.format(i, j)] = set(globals()['df2_{}_{}'.format(i, j)]['상권_코드'])
        if i == start_year and j == end_quarter - 2: # 2020년은 2분기까지 밖에 없으므로 조기 종료
            break
            
for i in range(start_year, end_year + 1):
    for j in range(start_quarter, end_quarter + 1):
        globals()['d2_{}_{}'.format(i, j)] = globals()['s2_{}_{}'.format(i, j)]
        if i == start_year and j == end_quarter - 2: # 2020년은 2분기까지 밖에 없으므로 조기 종료
            break

In [23]:
# 연도별, 분기별 빠진 상권의 상권 코드 출력

for i in range(start_year, end_year + 1):
    for j in range(start_quarter, end_quarter + 1):
        print("{}_{} : {}".format(i, j, globals()['d2_{}_{}'.format(i, j)]))
        if i == start_year and j == end_quarter - 2: # 2020년은 2분기까지 밖에 없으므로 조기 종료
            break

2020_1 : {1001344, 1000805, 1001435, 1001425, 1001272, 1001305, 1001434, 1001401, 1001372, 1001278, 1001311}
2020_2 : {1001344, 1000805, 1001435, 1001425, 1001272, 1001305, 1001434, 1001401, 1001372, 1001278, 1001311}
2019_1 : {1001435, 1001425, 1001428, 1001272, 1001305, 1001434, 1001401, 1001278, 1001311}
2019_2 : {1000805, 1001435, 1001389, 1001425, 1001428, 1001272, 1001305, 1001434, 1001401, 1001278, 1001311}
2019_3 : {1000805, 1001435, 1001425, 1001428, 1001272, 1001305, 1001434, 1001401, 1001278, 1001311}
2019_4 : {1000805, 1001435, 1001425, 1001272, 1001305, 1001434, 1001401, 1001278, 1001311}
2018_1 : {1001428, 1001272, 1001305, 1001434, 1001401, 1001311}
2018_2 : {1001428, 1001272, 1001305, 1001434, 1001401, 1001311}
2018_3 : {1001272, 1001305, 1001434, 1001401, 1001311}
2018_4 : {1001272, 1001305, 1001434, 1001401, 1001311}
2017_1 : {1001272, 1001401, 1001434, 1001311}
2017_2 : {1001272, 1001401, 1001434, 1001311}
2017_3 : {1001428, 1001272, 1001401, 1001434, 1001311}
2017_4 : {1001428, 1001272, 1001401, 1001434, 1001311}
2016_1 : {1001272, 1001305, 1001434, 1001401}
2016_2 : {1001272, 1001401, 1001434}
2016_3 : {1001272, 1001401, 1001434}
2016_4 : {1001272, 1001305, 1001434, 1001401, 1001311}
2015_1 : {1001425, 1001272, 1001305, 1001401, 1001311}
2015_2 : {1001425, 1001272, 1001305, 1001401, 1001311}
2015_3 : {1001425, 1001272, 1001305, 1001401, 1001311}
2015_4 : {1001425, 1001272, 1001305, 1001401, 1001311}

In [29]:
# 누락된 상권의 상권명 출력

market_code_list = list(df0['상권_코드'].unique())
market_name_list = list(df0['상권_코드_명'].unique())

# 누락된 상권 코드 저장
total_code_list = [] 
for i in range(start_year, end_year + 1):
    for j in range(start_quarter, end_quarter + 1):
        total_code_list.append(list(globals()['d2_{}_{}'.format(i, j)]))
        if i == start_year and j == end_quarter - 2: # 2020년은 2분기까지 밖에 없으므로 조기 종료
            break
            
# 상권 코드에 대응하는 상권명 저장
total_code_list = []
for code_list in total_code_list:
    for code in code_list:
        name_list = []
        ind = marekt_code_list.index(code)
        name = market_name_list[ind]
        name_list.append(name)
    total_code_list.append(name_list)
    

# 결과 출력
n = 0
for i in range(start_year, end_year + 1):
    for j in range(start_quarter, end_quarter + 1):
        print("{}_{} : {}".format(i, j, total_code_list[n]))
        if i == start_year and j == end_quarter - 2: # 2020년은 2분기까지 밖에 없으므로 조기 종료
            break

2020_1 : ['번동시장', '대학14길', '대신시장', '푸른터시장', '신설종합시장', '자양종합시장', '양남시장', '신곡종합시장', '녹번시장', '남평화시장', '동부청과시장']

2020_2 : ['번동시장', '대학14길', '대신시장', '푸른터시장', '신설종합시장', '자양종합시장', '양남시장', '신곡종합시장', '녹번시장', '남평화시장', '동부청과시장']

2019_1 : ['대신시장', '푸른터시장', '박미시장', '신설종합시장', '자양종합시장', '양남시장', '신곡종합시장', '남평화시장', '동부청과시장']

2019_2 : ['대학14길', '대신시장', '합정시장', '푸른터시장', '박미시장', '신설종합시장', '자양종합시장', '양남시장', '신곡종합시장', '남평화시장', '동부청과시장']

2019_3 : ['대학14길', '대신시장', '푸른터시장', '박미시장', '신설종합시장', '자양종합시장', '양남시장', '신곡종합시장', '남평화시장', '동부청과시장']

2019_4 : ['대학14길', '대신시장', '푸른터시장', '신설종합시장', '자양종합시장', '양남시장', '신곡종합시장', '남평화시장', '동부청과시장']

2018_1 : ['박미시장', '신설종합시장', '자양종합시장', '양남시장', '신곡종합시장', '동부청과시장']

2018_2 : ['박미시장', '신설종합시장', '자양종합시장', '양남시장', '신곡종합시장', '동부청과시장']

2018_3 : ['신설종합시장', '자양종합시장', '양남시장', '신곡종합시장', '동부청과시장']

2018_4 : ['신설종합시장', '자양종합시장', '양남시장', '신곡종합시장', '동부청과시장']

2017_1 : ['신설종합시장', '신곡종합시장', '양남시장', '동부청과시장']

2017_2 : ['신설종합시장', '신곡종합시장', '양남시장', '동부청과시장']

2017_3 : ['박미시장', '신설종합시장', '신곡종합시장', '양남시장', '동부청과시장']

2017_4 : ['박미시장', '신설종합시장', '신곡종합시장', '양남시장', '동부청과시장']

2016_1 : ['신설종합시장', '자양종합시장', '양남시장', '신곡종합시장']

2016_2 : ['신설종합시장', '신곡종합시장', '양남시장']

2016_3 : ['신설종합시장', '신곡종합시장', '양남시장']

2016_4 : ['신설종합시장', '자양종합시장', '양남시장', '신곡종합시장', '동부청과시장']

2015_1 : ['푸른터시장', '신설종합시장', '자양종합시장', '신곡종합시장', '동부청과시장']

2015_2 : ['푸른터시장', '신설종합시장', '자양종합시장', '신곡종합시장', '동부청과시장']

2015_3 : ['푸른터시장', '신설종합시장', '자양종합시장', '신곡종합시장', '동부청과시장']

2015_4 : ['푸른터시장', '신설종합시장', '자양종합시장', '신곡종합시장', '동부청과시장']

- 누락된 상권에도 생활 밀접 업종이 존재함. 즉, 점포가 존재하지 않아 누락된 것은 아님  
- 추정 매출 산정에 이용되는 세 가지 카드사에 해당하지 않는 카드 결제 혹은 현금 결제만이 이용하여서 누락되었다고 보기에는 무리가 있음  
- 각 카드사 혹은 우리마을가게 서비스에서 추정 매출을 어떻게 산정하는지 구체적으로 찾을 수 없었음   
- 우리마을가게 서비스에서는 누락된 상권의 추정 매출을 단순 0으로 처리함  
- 군집화를 통해 각 연도∙분기별로 유사한 상권을 찾아서 해당 상권의 추정 매출로 대체하는 방식?

## 3. 통합 데이터셋에서 결측치가 어떻게 나타나는지 조사

In [64]:
# 데이터 경로 설정
data_path_2 = './전체통합/'

# 통합 데이터 불러오기
df_m = pd.read_csv(data_path_2 + 'data_processed_final.csv')

In [65]:
df_m.head()

,Unnamed: 0,상권_구분_코드_명,상권_코드,상권_코드_명,기준_년_코드,기준_분기_코드,총_유동인구_수,집객시설_수,당월_매출_금액,총_직장_인구_수,총 상주인구 수,아파트_단지_수,아파트_평균_면적,아파트_평균_시가
0,0,전통시장,1001453,낙성대시장,2020.0,2.0,189157.0,4.0,3.994677e+09,10.0,568.0,6.0,37.0,123503739.0
1,1,전통시장,1001454,봉천제일종합시장,2020.0,2.0,82738.0,2.0,4.456344e+09,6.0,496.0,2.0,30.0,168357143.0
2,2,전통시장,1001474,도곡시장,2020.0,2.0,284809.0,7.0,1.162736e+10,57.0,241.0,1.0,67.0,639223684.0
3,3,전통시장,1001475,강남개포시장,2020.0,2.0,45750.0,4.0,3.526016e+09,138.0,NaN,NaN,NaN,NaN
4,4,전통시장,1001412,화곡본동시장,2020.0,2.0,184732.0,10.0,1.442403e+10,36.0,338.0,12.0,50.0,120212126.0

### (1) 유동인구 누락 데이터

In [66]:
df_m_people_null = df_m[df_m['총_유동인구_수'].isnull()]

In [67]:
df_m_people_null

,Unnamed: 0,상권_구분_코드_명,상권_코드,상권_코드_명,기준_년_코드,기준_분기_코드,총_유동인구_수,집객시설_수,당월_매출_금액,총_직장_인구_수,총 상주인구 수,아파트_단지_수,아파트_평균_면적,아파트_평균_시가
1439,1439,전통시장,1001278,남평화시장,2020.0,2.0,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN
2935,2935,전통시장,1001278,남평화시장,2020.0,1.0,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN
4431,4431,전통시장,1001278,남평화시장,2019.0,4.0,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN
5927,5927,전통시장,1001278,남평화시장,2019.0,3.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
7423,7423,전통시장,1001278,남평화시장,2019.0,2.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32735,32735,발달상권,1001086,고속터미널역,2015.0,1.0,NaN,NaN,1.018247e+11,14888.0,NaN,NaN,NaN,NaN
32813,32813,전통시장,1001269,동문시장,2015.0,1.0,NaN,NaN,9.880115e+06,NaN,NaN,NaN,NaN,NaN
32855,32855,전통시장,1001278,남평화시장,2015.0,1.0,NaN,NaN,1.127794e+09,152.0,NaN,NaN,NaN,NaN
32866,32866,전통시장,1001371,대조시장,2015.0,1.0,NaN,NaN,4.947208e+09,NaN,NaN,NaN,NaN,NaN
32876,32876,발달상권,1001020,장지역,2015.0,1.0,NaN,NaN,6.689008e+10,3724.0,NaN,NaN,NaN,NaN

In [68]:
df_m_people_null[['상권_구분_코드_명', '상권_코드', '상권_코드_명', '기준_년_코드', '기준_분기_코드']].isnull().sum()

상권_구분_코드_명    0
상권_코드         0
상권_코드_명       0
기준_년_코드       0
기준_분기_코드      0
dtype: int64

### (2) 추정매출 누락 데이터

In [69]:
df_m_profit_null = df_m[df_m['당월_매출_금액'].isnull()]

In [70]:
df_m_profit_null

,Unnamed: 0,상권_구분_코드_명,상권_코드,상권_코드_명,기준_년_코드,기준_분기_코드,총_유동인구_수,집객시설_수,당월_매출_금액,총_직장_인구_수,총 상주인구 수,아파트_단지_수,아파트_평균_면적,아파트_평균_시가
12,12,전통시장,1001425,푸른터시장,2020.0,2.0,70709.0,NaN,NaN,3.0,43.0,2.0,76.0,205074278.0
18,18,전통시장,1001372,녹번시장,2020.0,2.0,34267.0,2.0,NaN,22.0,NaN,NaN,NaN,NaN
797,797,골목상권,1000805,대학14길,2020.0,2.0,663198.0,20.0,NaN,61.0,2838.0,14.0,43.0,105359751.0
961,961,전통시장,1001434,양남시장,2020.0,2.0,27725.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
962,962,전통시장,1001435,대신시장,2020.0,2.0,101321.0,1.0,NaN,12.0,NaN,1.0,91.0,178866546.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31428,31428,전통시장,1001425,푸른터시장,2015.0,1.0,10228.0,NaN,NaN,NaN,42.0,1.0,85.0,175157895.0
32489,32489,전통시장,1001401,신곡종합시장,2015.0,1.0,20769.0,NaN,NaN,18.0,NaN,NaN,NaN,NaN
32742,32742,전통시장,1001311,동부청과시장,2015.0,1.0,15399.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32783,32783,전통시장,1001305,자양종합시장,2015.0,1.0,13662.0,NaN,NaN,NaN,54.0,1.0,60.0,219000000.0
32820,32820,전통시장,1001272,신설종합시장,2015.0,1.0,13439.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
df_m_profit_null[['상권_구분_코드_명', '상권_코드', '상권_코드_명', '기준_년_코드', '기준_분기_코드']].isnull().sum()

상권_구분_코드_명    0
상권_코드         0
상권_코드_명       0
기준_년_코드       0
기준_분기_코드      0
dtype: int64

#### 유동인구 및 추정매출은 누락되어도 데이터셋에 잘 나타난다. (연도, 분기 등 누락 X)